# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "wesdemos/centos9s-arm"
  config.vm.network "private_network", ip: "172.16.10.102"
  config.vm.hostname = "worker2"
  config.vm.box_download_insecure = true
  config.ssh.username = 'root'
  config.ssh.password = '123'
  config.ssh.insert_key = 'true'
  config.vm.provider "parallels" do |vb|
     vb.name = "worker2"
     vb.cpus = 1
     vb.memory = "1024"
     vb.linked_clone = false
  end
  
  # Chạy file install-docker-kube.sh sau khi nạp Box
  config.vm.provision "shell", path: "./../install-docker-kube.sh"

  # Chạy các lệnh shell
  config.vm.provision "shell", inline: <<-SHELL
    # Đặt pass 123 có tài khoản root và cho phép SSH
    echo "123" | passwd --stdin root
    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    systemctl reload sshd
# Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
cat >>/etc/hosts<<EOF
172.16.10.100 master
172.16.10.101 worker1
172.16.10.102 worker2
EOF

  SHELL
end